#!/bin/sh
set -e

case "$1" in
    configure)
        if ! getent group wclip >/dev/null; then
            addgroup --system wclip
        fi
        if ! getent passwd wclip >/dev/null; then
            adduser --system --ingroup wclip \
                --home /var/lib/wclip \
                --no-create-home \
                --gecos "wclip web-clipboard" \
                --shell /usr/sbin/nologin \
                wclip
        fi
        chown -R wclip:wclip /var/lib/wclip
        chmod 0750 /var/lib/wclip
        ;;
    abort-upgrade|abort-remove|abort-deconfigure)
        ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
